## 데이터 분석용 라이브러리

In [1]:
# 데이터 분석에 사용할 라이브러리
import pandas as pd
import numpy as np

In [2]:
import logging

logging.getLogger('matplotlib.font_manager').setLevel(logging.ERROR)

## 데이터 시각화용 라이브러리

In [3]:
# 데이터 시각화에 사용할 라이브러리
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

# 브라우저에서 바로 그려지도록
%matplotlib inline

# 그래프에 retina display 적용
%config InlineBackend.figure_format = 'retina'

# 유니코드에서  음수 부호설정
mpl.rc('axes', unicode_minus=False)

# 데이터 로드
- [타이타닉 데이터 로드](https://www.kaggle.com/c/titanic/)

In [4]:
import os

# 현재 노트북 기준으로 프로젝트 루트를 찾아서 data 폴더 경로 고정
BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))  # COURSE_MACHINE_LEARNING 폴더
DATA_PATH = os.path.join(BASE_DIR, "data")

df = pd.read_csv(os.path.join(DATA_PATH, "Titanic.csv"))

In [5]:
df.shape, df.columns

((891, 12),
 Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
        'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
       dtype='str'))

In [6]:
df.columns = [col.lower() for col in df.columns] # 컬럼명 소문자로 변환
df.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

## 데이터 분리

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
SEED = 42

X_tr, X_te = train_test_split(df, random_state=SEED, test_size = 0.2)
X_tr = X_tr.reset_index(drop=True)
X_te = X_te.reset_index(drop=True)

X_tr.shape, X_te.shape

((712, 12), (179, 12))

In [9]:
X_tr.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,332,0,1,"Partner, Mr. Austen",male,45.5,0,0,113043,28.5000,C124,S
1,734,0,2,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S
2,383,0,3,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S
3,705,0,3,"Hansen, Mr. Henrik Juul",male,26.0,1,0,350025,7.8542,NaN,S
4,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S

In [10]:
X_tr.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [11]:
new_survived = pd.Categorical(X_tr['survived'])
new_survived = new_survived.rename_categories(["Died","Survived"])
print(new_survived[:5])
new_survived.describe()

['Died', 'Died', 'Died', 'Died', 'Died']
Categories (2, str): ['Died', 'Survived']

            counts     freqs
categories
Died           444  0.623596
Survived       268  0.376404

## 데이터 확인

In [12]:
X_tr.info()

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  712 non-null    int64
 1   survived     712 non-null    int64
 2   pclass       712 non-null    int64
 3   name         712 non-null    str
 4   sex          712 non-null    str
 5   age          572 non-null    float64
 6   sibsp        712 non-null    int64
 7   parch        712 non-null    int64
 8   ticket       712 non-null    str
 9   fare         712 non-null    float64
 10  cabin        159 non-null    str
 11  embarked     710 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 66.9 KB

In [13]:
X_tr.describe(include="all")

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
count,712.000000,712.000000,712.000000,712,712,572.000000,712.000000,712.000000,712,712.000000,159,710
unique,NaN,NaN,NaN,712,2,NaN,NaN,NaN,558,NaN,117,3
top,NaN,NaN,NaN,"Partner, Mr. Austen",male,NaN,NaN,NaN,CA. 2343,NaN,C23 C25 C27,S
freq,NaN,NaN,NaN,1,467,NaN,NaN,NaN,7,NaN,4,525
mean,448.234551,0.376404,2.330056,NaN,NaN,29.498846,0.553371,0.379213,NaN,32.586276,NaN,NaN
std,256.731423,0.484824,0.824584,NaN,NaN,14.500059,1.176404,0.791669,NaN,51.969529,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,224.750000,0.000000,2.000000,NaN,NaN,21.000000,0.000000,0.000000,NaN,7.925000,NaN,NaN
50%,453.500000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,673.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,30.500000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [14]:
X_tr.describe(include=np.number)

,passengerid,survived,pclass,age,sibsp,parch,fare
count,712.000000,712.000000,712.000000,572.000000,712.000000,712.000000,712.000000
mean,448.234551,0.376404,2.330056,29.498846,0.553371,0.379213,32.586276
std,256.731423,0.484824,0.824584,14.500059,1.176404,0.791669,51.969529
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,224.750000,0.000000,2.000000,21.000000,0.000000,0.000000,7.925000
50%,453.500000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,673.500000,1.000000,3.000000,38.000000,1.000000,0.000000,30.500000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [15]:
X_tr.describe(exclude=np.number)

                       name   sex    ticket        cabin embarked
count                   712   712       712          159      710
unique                  712     2       558          117        3
top     Partner, Mr. Austen  male  CA. 2343  C23 C25 C27        S
freq                      1   467         7            4      525

In [16]:
X_tr.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,332,0,1,"Partner, Mr. Austen",male,45.5,0,0,113043,28.5000,C124,S
1,734,0,2,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S
2,383,0,3,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S
3,705,0,3,"Hansen, Mr. Henrik Juul",male,26.0,1,0,350025,7.8542,NaN,S
4,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S

In [17]:
X_tr.tail()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
707,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S
708,271,0,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S
709,861,0,3,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,NaN,S
710,436,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S
711,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S

## 타겟 데이터 확인

In [18]:
new_survived = pd.Categorical(X_tr["survived"])
new_survived = new_survived.rename_categories(["Died","Survived"])

new_survived.describe()

            counts     freqs
categories
Died           444  0.623596
Survived       268  0.376404

# Data Cleaning

## 필요없는 데이터

In [19]:
X_tr['passengerid'].nunique(), X_tr.shape[0]

(712, 712)

In [20]:
# passengerid는 전체 데이터가 unique하기 때문에 삭제
X_tr.drop('passengerid', axis=1, inplace=True)
X_te.drop('passengerid', axis=1, inplace=True)

X_tr.columns

Index(['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked'],
      dtype='str')

### 결측치 처리

In [21]:
(X_tr.isnull().sum() / X_tr.shape[0]).round(4)\
  .sort_values(ascending=False) # 각 걸럼별 결측치 비율

cabin       0.7767
age         0.1966
embarked    0.0028
name        0.0000
pclass      0.0000
survived    0.0000
sex         0.0000
parch       0.0000
sibsp       0.0000
fare        0.0000
ticket      0.0000
dtype: float64

In [22]:
print(f'before: {X_tr.shape} / isnull().sum(): {X_tr.isnull().sum().sum()}')
# 결측치가 있는 행 제거 : X_tr.dropna(axis=0)
X_tr = X_tr.drop('cabin', axis=1)
X_te = X_te.drop('cabin', axis=1)
print(f'after: {X_tr.shape} / isnull().sum(): {X_tr.isnull().sum().sum()}')

before: (712, 11) / isnull().sum(): 695
after: (712, 10) / isnull().sum(): 142

In [23]:
X_tr['age'] = X_tr['age'].fillna(X_tr['age'].median())
X_te['age'] = X_te['age'].fillna(X_tr['age'].median())

In [24]:
embarked_mode = X_tr['embarked'].mode().values[0]

X_tr['embarked'] = X_tr['embarked'].fillna(embarked_mode)
X_te['embarked'] = X_te['embarked'].fillna(embarked_mode)

In [25]:
X_tr.isnull().sum().sum(), X_te.isnull().sum().sum()

(np.int64(0), np.int64(0))

# Feature Extraction
> 기존 Feature에 기반하여 새로운 Feature들을 생성

## 데이터 타입

In [26]:
X_tr.info()

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  712 non-null    int64
 1   pclass    712 non-null    int64
 2   name      712 non-null    str
 3   sex       712 non-null    str
 4   age       712 non-null    float64
 5   sibsp     712 non-null    int64
 6   parch     712 non-null    int64
 7   ticket    712 non-null    str
 8   fare      712 non-null    float64
 9   embarked  712 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 55.8 KB

#### 수치형 데이터 타입 변환

In [27]:
df_number = X_tr.select_dtypes(include=np.number)
df_number.columns

Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'], dtype='str')

In [28]:
df_number.info()

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  712 non-null    int64
 1   pclass    712 non-null    int64
 2   age       712 non-null    float64
 3   sibsp     712 non-null    int64
 4   parch     712 non-null    int64
 5   fare      712 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 33.5 KB

In [29]:
df_number.head()

   survived  pclass   age  sibsp  parch     fare
0         0       1  45.5      0      0  28.5000
1         0       2  23.0      0      0  13.0000
2         0       3  32.0      0      0   7.9250
3         0       3  26.0      1      0   7.8542
4         0       3   6.0      4      2  31.2750

In [30]:
# survived
X_tr["survived"] = X_tr["survived"].astype("int32")
X_te["survived"] = X_te["survived"].astype("int32")

In [31]:
# pclass
X_tr['pclass'].unique()

array([1, 2, 3])

In [32]:
X_tr["pclass"] = X_tr["pclass"].astype("category")
X_te["pclass"] = X_te["pclass"].astype("category")

In [33]:
# age
X_tr["age"] = X_tr["age"].astype("int32")
X_te["age"] = X_te["age"].astype("int32")

In [34]:
# sibsp
X_tr['sibsp'].unique()

array([0, 1, 4, 3, 2, 8, 5])

In [35]:
X_tr["sibsp"] = X_tr["sibsp"].astype("category")
X_te["sibsp"] = X_te["sibsp"].astype("category")

In [36]:
# parch
X_tr['parch'].unique()

array([0, 2, 1, 6, 4, 3, 5])

In [37]:
X_tr["parch"] = X_tr["parch"].astype("category")
X_te["parch"] = X_te["parch"].astype("category")

In [38]:
# fare
X_tr["fare"] = X_tr["fare"].astype("float32")
X_te["fare"] = X_te["fare"].astype("float32")

In [39]:
X_tr.info()

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  712 non-null    int32
 1   pclass    712 non-null    category
 2   name      712 non-null    str
 3   sex       712 non-null    str
 4   age       712 non-null    int32
 5   sibsp     712 non-null    category
 6   parch     712 non-null    category
 7   ticket    712 non-null    str
 8   fare      712 non-null    float32
 9   embarked  712 non-null    str
dtypes: category(3), float32(1), int32(2), str(4)
memory usage: 32.9 KB

#### 범주형 데이터 타입 변환

In [40]:
df_object = X_tr.select_dtypes(include='object')
df_object.columns

C:\Users\Playdata\AppData\Local\Temp\ipykernel_3624\185119966.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_object = X_tr.select_dtypes(include='object')

Index(['name', 'sex', 'ticket', 'embarked'], dtype='str')

In [41]:
df_object.head()

                                 name     sex             ticket embarked
0                 Partner, Mr. Austen    male             113043        S
1          Berriman, Mr. William John    male              28425        S
2                  Tikkanen, Mr. Juho    male  STON/O 2. 3101293        S
3             Hansen, Mr. Henrik Juul    male             350025        S
4  Andersson, Miss. Ebba Iris Alfrida  female             347082        S

In [42]:
X_tr["sex"] = X_tr["sex"].astype("category")
X_te["sex"] = X_te["sex"].astype("category")

In [43]:
X_tr["embarked"] = X_tr["embarked"].astype("category")
X_te["embarked"] = X_te["embarked"].astype("category")

In [44]:
X_tr.info()

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  712 non-null    int32
 1   pclass    712 non-null    category
 2   name      712 non-null    str
 3   sex       712 non-null    category
 4   age       712 non-null    int32
 5   sibsp     712 non-null    category
 6   parch     712 non-null    category
 7   ticket    712 non-null    str
 8   fare      712 non-null    float32
 9   embarked  712 non-null    category
dtypes: category(5), float32(1), int32(2), str(2)
memory usage: 23.5 KB

In [45]:
X_tr.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,0,1,"Partner, Mr. Austen",male,45,0,0,113043,28.5000,S
1,0,2,"Berriman, Mr. William John",male,23,0,0,28425,13.0000,S
2,0,3,"Tikkanen, Mr. Juho",male,32,0,0,STON/O 2. 3101293,7.9250,S
3,0,3,"Hansen, Mr. Henrik Juul",male,26,1,0,350025,7.8542,S
4,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6,4,2,347082,31.2750,S

## 문자열

In [46]:
df_object = X_tr.select_dtypes(include='object')
df_object.columns

C:\Users\Playdata\AppData\Local\Temp\ipykernel_3624\185119966.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_object = X_tr.select_dtypes(include='object')

Index(['name', 'ticket'], dtype='str')

In [47]:
df_object.head()

                                 name             ticket
0                 Partner, Mr. Austen             113043
1          Berriman, Mr. William John              28425
2                  Tikkanen, Mr. Juho  STON/O 2. 3101293
3             Hansen, Mr. Henrik Juul             350025
4  Andersson, Miss. Ebba Iris Alfrida             347082

In [48]:
df_object.describe()

                       name    ticket
count                   712       712
unique                  712       558
top     Partner, Mr. Austen  CA. 2343
freq                      1         7

### 공백제거
> 앞뒤 공백제거, lstrip , rstrip

In [49]:
X_tr["name"] = X_tr["name"].map(lambda x: x.strip())
X_tr["ticket"] = X_tr["ticket"].map(lambda x: x.strip())

X_te["name"] = X_te["name"].map(lambda x: x.strip())
X_te["ticket"] = X_te["ticket"].map(lambda x: x.strip())

In [50]:
df_object.head()

                                 name             ticket
0                 Partner, Mr. Austen             113043
1          Berriman, Mr. William John              28425
2                  Tikkanen, Mr. Juho  STON/O 2. 3101293
3             Hansen, Mr. Henrik Juul             350025
4  Andersson, Miss. Ebba Iris Alfrida             347082

### 문자열 포함 여부

In [51]:
dict_designation = {
    'Mr.': '남성',
    'Master.': '남성',
    'Sir.': '남성',
    'Miss.': '미혼 여성',
    'Mrs.': '기혼 여성',
    'Ms.': '미혼/기혼 여성',
    'Lady.': '숙녀',
    'Mlle.': '아가씨',
    # 직업
    'Dr.': '의사',
    'Rev.': '목사',
    'Major.': '계급',
    'Don.': '교수',
    'Col.': '군인',
    'Capt.': '군인',
    # 귀족
    'Mme.': '영부인',
    'Countess.': '백작부인',
    'Jonkheer.': '귀족'
}

In [52]:
dict_designation.keys()

dict_keys(['Mr.', 'Master.', 'Sir.', 'Miss.', 'Mrs.', 'Ms.', 'Lady.', 'Mlle.', 'Dr.', 'Rev.', 'Major.', 'Don.', 'Col.', 'Capt.', 'Mme.', 'Countess.', 'Jonkheer.'])

In [53]:
# X_tr['name'].map(lambda x: x) ->
x = 'Andersson, Miss. Ebba Iris Alfrida	'
x

'Andersson, Miss. Ebba Iris Alfrida\t'

In [54]:
'Mr.' in x

False

In [55]:
'Miss.' in x

True

In [56]:
for key in dict_designation.keys():
  result = 'unknown'
  if key in x:
    result = key
    break

print(result)

Miss.

In [57]:
dict_designation = {
    'Mr.': '남성',
    'Master.': '남성',
    'Sir.': '남성',
    'Miss.': '미혼 여성',
    'Mrs.': '기혼 여성',
    'Ms.': '미혼/기혼 여성',
    'Lady.': '숙녀',
    'Mlle.': '아가씨',
    # 직업
    'Dr.': '의사',
    'Rev.': '목사',
    'Major.': '계급',
    'Don.': '교수',
    'Col.': '군인',
    'Capt.': '군인',
    # 귀족
    'Mme.': '영부인',
    'Countess.': '백작부인',
    'Jonkheer.': '귀족'
}

def add_designation(name): # 호칭 함수
  designation = "unknown"
  for key in dict_designation.keys():
    if key in name:
      designation = key
      break
  return designation

X_tr['designation'] = X_tr['name'].map(
    lambda x: add_designation(x))
X_te['designation'] = X_te['name'].map(
    lambda x: add_designation(x))

X_tr[['name', 'designation']].head()

                                 name designation
0                 Partner, Mr. Austen         Mr.
1          Berriman, Mr. William John         Mr.
2                  Tikkanen, Mr. Juho         Mr.
3             Hansen, Mr. Henrik Juul         Mr.
4  Andersson, Miss. Ebba Iris Alfrida       Miss.

In [58]:
X_tr[['name', 'designation']].tail()

                                 name designation
707  Salkjelsvik, Miss. Anna Kristine       Miss.
708             Cairns, Mr. Alexander         Mr.
709           Hansen, Mr. Claus Peter         Mr.
710         Carter, Miss. Lucile Polk       Miss.
711         White, Mr. Richard Frasar         Mr.

In [59]:
cond = X_tr['designation'] == "unknown"
X_tr.loc[cond].head()

Empty DataFrame
Columns: [survived, pclass, name, sex, age, sibsp, parch, ticket, fare, embarked, designation]
Index: []

In [60]:
X_tr[X_tr['designation'] == "unknown"].shape

(0, 11)

In [61]:
cond = X_te['designation'] == "unknown"
X_te.loc[cond].head()

Empty DataFrame
Columns: [survived, pclass, name, sex, age, sibsp, parch, ticket, fare, embarked, designation]
Index: []

### 문자열 분리

In [62]:
X_tr['name'].head()

0                   Partner, Mr. Austen
1            Berriman, Mr. William John
2                    Tikkanen, Mr. Juho
3               Hansen, Mr. Henrik Juul
4    Andersson, Miss. Ebba Iris Alfrida
Name: name, dtype: str

In [63]:
# 1. Mr. 이런거 삭제... -> replace()
# 2. , 이걸로 나누기.... -> split()
# 3. 라스트 네임 추출
# 4. 새로운 컬럼에 적용

def get_last_name(name):
  last_name = None
  try:

    for key in dict_designation.keys(): # 이니셜을 다 조회하기
      if key in name: # 이니셜이 있는지 확인하기
        name = name.replace(key,'') # 이니셜을 제거하기
        last_name = name.split(',')[1].strip() # 라스트 네임 추출하기
  except:
    pass
  return last_name

X_tr['last_name'] = X_tr['name'].map(lambda x: get_last_name(x))
X_te['last_name'] = X_te['name'].map(lambda x: get_last_name(x))

X_tr[['name', 'last_name']].head()

                                 name          last_name
0                 Partner, Mr. Austen             Austen
1          Berriman, Mr. William John       William John
2                  Tikkanen, Mr. Juho               Juho
3             Hansen, Mr. Henrik Juul        Henrik Juul
4  Andersson, Miss. Ebba Iris Alfrida  Ebba Iris Alfrida

In [64]:
X_tr['first_name'] = X_tr['name'].map(
    lambda x: x.split(',')[0].strip())
X_te['first_name'] = X_te['name'].map(
    lambda x: x.split(',')[0].strip())

X_tr[['name', 'last_name', 'first_name']].head()

                                 name          last_name first_name
0                 Partner, Mr. Austen             Austen    Partner
1          Berriman, Mr. William John       William John   Berriman
2                  Tikkanen, Mr. Juho               Juho   Tikkanen
3             Hansen, Mr. Henrik Juul        Henrik Juul     Hansen
4  Andersson, Miss. Ebba Iris Alfrida  Ebba Iris Alfrida  Andersson

In [65]:
X_tr.tail()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,designation,last_name,first_name
707,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21,0,0,343120,7.650000,S,Miss.,Anna Kristine,Salkjelsvik
708,0,1,"Cairns, Mr. Alexander",male,28,0,0,113798,31.000000,S,Mr.,Alexander,Cairns
709,0,3,"Hansen, Mr. Claus Peter",male,41,2,0,350026,14.108300,S,Mr.,Claus Peter,Hansen
710,1,1,"Carter, Miss. Lucile Polk",female,14,1,2,113760,120.000000,S,Miss.,Lucile Polk,Carter
711,0,1,"White, Mr. Richard Frasar",male,21,0,1,35281,77.287498,S,Mr.,Richard Frasar,White

In [66]:
X_tr['ticket']

0                 113043
1                  28425
2      STON/O 2. 3101293
3                 350025
4                 347082
             ...
707               343120
708               113798
709               350026
710               113760
711                35281
Name: ticket, Length: 712, dtype: str

In [67]:
def add_ticket_number(ticket):
  try:
    ticket_split = ticket.split(' ')
    return int(ticket_split[-1])
  except:
    return 0 # ticket이 LINE인 경우

X_tr['ticket_number'] = X_tr['ticket'].map(lambda x: add_ticket_number(x)).astype("int32")
X_te['ticket_number'] = X_te['ticket'].map(lambda x: add_ticket_number(x)).astype("int32")

X_tr[['ticket_number', 'ticket']].head()

   ticket_number             ticket
0         113043             113043
1          28425              28425
2        3101293  STON/O 2. 3101293
3         350025             350025
4         347082             347082

In [68]:
X_tr[['ticket_number', 'ticket']].info()

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ticket_number  712 non-null    int32
 1   ticket         712 non-null    str
dtypes: int32(1), str(1)
memory usage: 8.5 KB

## 집계

### 피봇 테이블

In [69]:
X_tr.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,designation,last_name,first_name,ticket_number
0,0,1,"Partner, Mr. Austen",male,45,0,0,113043,28.5000,S,Mr.,Austen,Partner,113043
1,0,2,"Berriman, Mr. William John",male,23,0,0,28425,13.0000,S,Mr.,William John,Berriman,28425
2,0,3,"Tikkanen, Mr. Juho",male,32,0,0,STON/O 2. 3101293,7.9250,S,Mr.,Juho,Tikkanen,3101293
3,0,3,"Hansen, Mr. Henrik Juul",male,26,1,0,350025,7.8542,S,Mr.,Henrik Juul,Hansen,350025
4,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6,4,2,347082,31.2750,S,Miss.,Ebba Iris Alfrida,Andersson,347082

In [70]:
df_pivot = pd.pivot_table(X_tr
    , index='pclass', values='fare', aggfunc='mean').reset_index()
df_pivot.rename(columns = {'fare' : 'fare_mean_by_pclass'}, inplace = True)
df_pivot #.head()

  pclass  fare_mean_by_pclass
0      1            89.253914
1      2            20.575939
2      3            13.934861

In [71]:
print(f'before: {X_tr.shape}')
X_tr = pd.merge(X_tr,df_pivot,how="left",on="pclass")
X_te = pd.merge(X_te,df_pivot,how="left",on="pclass")
print(f'after: {X_tr.shape}')

X_tr[['pclass', 'fare', 'fare_mean_by_pclass']].head()

before: (712, 14)
after: (712, 15)

  pclass     fare  fare_mean_by_pclass
0      1  28.5000            89.253914
1      2  13.0000            20.575939
2      3   7.9250            13.934861
3      3   7.8542            13.934861
4      3  31.2750            13.934861

### 그룹

In [72]:
agg_dict = {
    "survived" : "mean" , "sibsp" : "nunique"
    , "parch" : "nunique" }
df_groupby = X_tr.groupby("pclass")\
  .agg(agg_dict).reset_index()

df_groupby

  pclass  survived  sibsp  parch
0      1  0.607362      4      4
1      2  0.483444      4      4
2      3  0.241206      7      7

In [73]:
agg_dict = {
    "survived" : "mean" , "sibsp" : "nunique"
    , "parch" : "nunique" }
df_groupby = X_tr.groupby("pclass")\
  .agg(agg_dict).reset_index()

df_groupby.rename(
    columns = {
        'survived' : 'survived_by_pclass'
        , 'sibsp' : 'len_sibsp_by_pclass'
        , 'parch' : 'len_parch_by_pclass'}
    , inplace = True)
df_groupby

  pclass  survived_by_pclass  len_sibsp_by_pclass  len_parch_by_pclass
0      1            0.607362                    4                    4
1      2            0.483444                    4                    4
2      3            0.241206                    7                    7

In [74]:
print(f'before: {X_tr.shape}')
X_tr = pd.merge(X_tr,df_groupby,how="left",on="pclass")
X_te = pd.merge(X_te,df_groupby,how="left",on="pclass")
print(f'after: {X_tr.shape}')
X_tr.head()

before: (712, 15)
after: (712, 18)

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,designation,last_name,first_name,ticket_number,fare_mean_by_pclass,survived_by_pclass,len_sibsp_by_pclass,len_parch_by_pclass
0,0,1,"Partner, Mr. Austen",male,45,0,0,113043,28.5000,S,Mr.,Austen,Partner,113043,89.253914,0.607362,4,4
1,0,2,"Berriman, Mr. William John",male,23,0,0,28425,13.0000,S,Mr.,William John,Berriman,28425,20.575939,0.483444,4,4
2,0,3,"Tikkanen, Mr. Juho",male,32,0,0,STON/O 2. 3101293,7.9250,S,Mr.,Juho,Tikkanen,3101293,13.934861,0.241206,7,7
3,0,3,"Hansen, Mr. Henrik Juul",male,26,1,0,350025,7.8542,S,Mr.,Henrik Juul,Hansen,350025,13.934861,0.241206,7,7
4,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6,4,2,347082,31.2750,S,Miss.,Ebba Iris Alfrida,Andersson,347082,13.934861,0.241206,7,7

## 데이터 변환/조합
> apply(), map() 등 사용

In [75]:
def sub_age(age):
  return age // 10

X_tr['sub_age'] = X_tr['age'].map(lambda x: sub_age(x))
X_te['sub_age'] = X_te['age'].map(lambda x: sub_age(x))
X_tr[['age', 'sub_age']].head()

   age  sub_age
0   45        4
1   23        2
2   32        3
3   26        2
4    6        0

In [76]:
def add_sub_embarked(row):
  return str(row['embarked']) + str(row['pclass']) + str(row['sibsp']) + str(row['parch'])

X_tr['sub_embarked'] = X_tr.apply(lambda row: add_sub_embarked(row), axis=1)
X_te['sub_embarked'] = X_te.apply(lambda row: add_sub_embarked(row), axis=1)
X_tr.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,designation,last_name,first_name,ticket_number,fare_mean_by_pclass,survived_by_pclass,len_sibsp_by_pclass,len_parch_by_pclass,sub_age,sub_embarked
0,0,1,"Partner, Mr. Austen",male,45,0,0,113043,28.5000,S,Mr.,Austen,Partner,113043,89.253914,0.607362,4,4,4,S100
1,0,2,"Berriman, Mr. William John",male,23,0,0,28425,13.0000,S,Mr.,William John,Berriman,28425,20.575939,0.483444,4,4,2,S200
2,0,3,"Tikkanen, Mr. Juho",male,32,0,0,STON/O 2. 3101293,7.9250,S,Mr.,Juho,Tikkanen,3101293,13.934861,0.241206,7,7,3,S300
3,0,3,"Hansen, Mr. Henrik Juul",male,26,1,0,350025,7.8542,S,Mr.,Henrik Juul,Hansen,350025,13.934861,0.241206,7,7,2,S310
4,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6,4,2,347082,31.2750,S,Miss.,Ebba Iris Alfrida,Andersson,347082,13.934861,0.241206,7,7,0,S342

## [진행바(tqdm)](https://github.com/tqdm/tqdm#table-of-contents)
- 파이썬에서 반복 루프를 돌다 보면 진행이 얼마나 되었는지 Progress Bar를 통해 알 수 있습니다.
- 이처럼 반복문에서 진행률을 Progress Bar로 표현해주고 남은 시간 정보까지 알려주는 것이 바로 `tqdm`입니다.

In [77]:
from tqdm.auto import tqdm

In [78]:
i=0
for i in np.random.rand(10000000):
    i = i**2

In [79]:
i=0
for i in tqdm(np.random.rand(10000000)):
    i = i**2

  0%|          | 0/10000000 [00:00<?, ?it/s]

### tqdm 파라미터

- `iterable`: 반복자 객체
- `desc`: 진행바 앞에 텍스트 출력
- `total`: int, 전체 반복량
- `leave`: bool, default로 True (진행상태 잔상이 남음)
- `ncols`: 진행바 컬럼길이
  - width값으로 pixel 단위로 보임
- `mininterval`, `maxinterval`: 업데이트 주기
  - 기본은 mininterval=0.1 sec, maxinterval=10 sec
- `miniters`: Minimum progress display update interval, in iterations.
- `ascii`: True로 하면 `#`문자로 진행바가 표시됨
- `initial`: 진행 시작값. 기본은 0
- `colour`: 'blue', '#0000ff' (헥스코드로도 입력 가능)
- `position`: 바 위치 설정. 여러개의 바 관리할 때 지정

In [80]:
import time

iterable = ['a','b','c']
for i in tqdm(
    iterable, # 반복가능한 iterable 객체
    desc = 'Description', # 프로그레스 바 맨 앞에 나타날 문구
    colour = 'blue', # '#0000ff' 헥스코드로도 입력 가능
    position = 0 # 바 위치 설정. 여러개의 바 관리할 때 지정
            ):
  time.sleep(0.5)

Description:   0%|          | 0/3 [00:00<?, ?it/s]

### Manual
- with 구문을 사용해서 tqdm을 수동으로 컨트롤한다.
- update()로 수동으로 진행률을 증가 시킨다.

In [81]:
iterable = ['a', 'b', 'c', 'd', 'e']
with tqdm(iterable,
              total = len(iterable), ## 전체 진행수
              desc = 'Description', ## 진행률 앞쪽 출력 문장
              ascii = ' =', ## 바 모양, 첫 번째 문자는 공백이어야 작동
              leave = True, ## True 반복문 완료시 진행률 출력 남김. False 남기지 않음.
             ) as pbar:
  for c in pbar:
      pbar.set_description(f'Current Character "{c}"') ## 또는 pbar.desc = f'Current Character "{c}"'
      time.sleep(0.2)

Description:   0%|          | 0/5 [00:00<?, ?it/s]

In [82]:
iterable = ['a', 'b', 'c', 'd', 'e']
pbar = tqdm(iterable,
              total = len(iterable), ## 전체 진행수
              desc = 'Description', ## 진행률 앞쪽 출력 문장
              ascii = ' =', ## 바 모양, 첫 번째 문자는 공백이어야 작동
              leave = True, ## True 반복문 완료시 진행률 출력 남김. False 남기지 않음.
             )
for c in pbar:
    pbar.set_description(f'Current Character "{c}"') ## 또는 pbar.desc = f'Current Character "{c}"'
    time.sleep(0.2)
pbar.close() # with를 사용하지 않은 경우에는 꼭 close()를 해야함!

Description:   0%|          | 0/5 [00:00<?, ?it/s]

### 이중 루프(Nested Loop)
- 두개 이상 for문이 있는 경우

In [83]:
import time

for outer in tqdm([10, 20, 30, 40, 50], desc='outer', position=0): ## 출력되는 라인을 나타내는 position을 0 으로 두고
    for inner in tqdm(range(outer), desc='inner', position=1, leave=False): ## 안쪽 루프의 진행률 출력은 그 아랫줄인 position = 1 로 설정하는 것이다.
        time.sleep(1)

outer:   0%|          | 0/5 [00:00<?, ?it/s]

inner:   0%|          | 0/10 [00:00<?, ?it/s]

inner:   0%|          | 0/20 [00:00<?, ?it/s]

inner:   0%|          | 0/30 [00:00<?, ?it/s]

inner:   0%|          | 0/40 [00:00<?, ?it/s]

inner:   0%|          | 0/50 [00:00<?, ?it/s]

- Jupyter Notebook

In [84]:
from tqdm.notebook import tqdm
import time

for outer in tqdm([10, 20, 30, 40, 50], desc='outer', position=0):
    for inner in tqdm(range(outer), desc='inner', position=1, leave=False):
        time.sleep(0.01)

outer:   0%|          | 0/5 [00:00<?, ?it/s]

inner:   0%|          | 0/10 [00:00<?, ?it/s]

inner:   0%|          | 0/20 [00:00<?, ?it/s]

inner:   0%|          | 0/30 [00:00<?, ?it/s]

inner:   0%|          | 0/40 [00:00<?, ?it/s]

inner:   0%|          | 0/50 [00:00<?, ?it/s]

### with pandas

In [85]:
tqdm.pandas() # 판다스에서 progress_apply 메소드를 사용할수 있게 된다.

In [86]:
import time

def do_apply(x):
    time.sleep(0.01)
    return x

tmp = df.progress_apply(do_apply,axis = 1)

  0%|          | 0/891 [00:00<?, ?it/s]