# SQLAlchemy with MySQL 기초

이 노트북은 SQLAlchemy 2.x 방식으로 MySQL에 연결하고 SQL 실행, Core CRUD, ORM 기초를 실습합니다.

SQLAlchemy는 SQL을 몰라도 되는 도구가 아닙니다. SQL 실행과 테이블/객체 작업을 Python 코드 안에서 일관된 방식으로 다루게 해주는 도구입니다.

## 1. 패키지와 접속 정보 준비

MySQL 드라이버는 기존 강의와 같은 `PyMySQL`을 사용하고, SQLAlchemy URL은 `mysql+pymysql://...` 형식으로 작성합니다.

In [1]:
import os
from datetime import datetime
from decimal import Decimal

import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import Column, DateTime, Integer, MetaData, Numeric, String, Table, create_engine, delete, func, insert, select, text, update
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column

# .env 파일의 DB 접속 정보를 읽어옵니다.
# 실습 환경마다 host, user, password가 다를 수 있으므로 코드에 직접 고정하지 않습니다.
load_dotenv()

# SQLAlchemy는 DB 작업 방식을 통일해 주는 라이브러리입니다.
# 다만 MySQL 서버와 실제로 통신하려면 PyMySQL 같은 DB 드라이버가 필요합니다.
# 그래서 접속 URL에 mysql+pymysql처럼 "DB 종류 + 드라이버"를 함께 적습니다.
DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "3306"),
    "database": os.getenv("DB_NAME", "examplesdb"),
    "user": os.getenv("DB_USER", "urstory"),
    "password": os.getenv("DB_PASSWORD", "u1234"),
}

# SQLAlchemy 접속 URL 형식:
# mysql+pymysql://사용자:비밀번호@호스트:포트/데이터베이스명?charset=utf8mb4
# charset=utf8mb4는 한글 데이터를 안전하게 다루기 위해 붙입니다.
DATABASE_URL = (
    f"mysql+pymysql://{DB_CONFIG['user']}:{DB_CONFIG['password']}"
    f"@{DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['database']}?charset=utf8mb4"
)

# Engine은 SQLAlchemy에서 DB로 가는 출입구 역할을 합니다.
# 필요할 때 연결을 만들고, 연결을 효율적으로 재사용하는 connection pool도 관리합니다.
# echo=True로 바꾸면 SQLAlchemy가 실제로 만든 SQL을 콘솔에서 볼 수 있어 학습에 도움이 됩니다.
engine = create_engine(DATABASE_URL, echo=False)

# 노트북 화면에 접속 URL을 확인하되, 비밀번호는 그대로 노출하지 않도록 마스킹합니다.
DATABASE_URL.replace(DB_CONFIG["password"], "****")

'mysql+pymysql://urstory:****@localhost:3306/examplesdb?charset=utf8mb4'

## 2. 연결 확인

`engine.connect()`로 연결을 얻고, `text()`로 SQL 문자열을 실행합니다.

In [2]:
# engine.connect()는 SQL을 실행할 연결을 하나 빌려옵니다.
# with 문을 사용하면 블록이 끝날 때 연결이 자동으로 반환됩니다.
with engine.connect() as conn:
    # text()는 문자열 SQL을 SQLAlchemy가 실행할 수 있는 SQL 객체로 감싸 줍니다.
    # 순수 SQL을 직접 실행하고 싶을 때 가장 단순한 방식입니다.
    result = conn.execute(text("SELECT VERSION() AS version"))

    # mappings()를 붙이면 결과 행을 튜플이 아니라 dict와 비슷한 형태로 받을 수 있습니다.
    # one()은 결과가 정확히 한 행이라고 기대할 때 사용합니다.
    row = result.mappings().one()

row

{'version': '9.7.1'}

## 3. text()로 SQL 직접 실행하기

SQLAlchemy에서도 SQL을 직접 작성할 수 있습니다. 값은 `:name` 형태의 바인딩 파라미터로 전달합니다.

In [3]:
with engine.connect() as conn:
    rows = conn.execute(
        text("""
        SELECT
            table_name
        FROM information_schema.tables
        WHERE table_schema = :schema_name
        ORDER BY table_name
        LIMIT 10
        """),
        # :schema_name은 SQLAlchemy의 named parameter입니다.
        # 문자열을 SQL에 직접 붙이지 않고 값만 따로 넘기면 SQL Injection 위험을 줄일 수 있습니다.
        {"schema_name": DB_CONFIG["database"]},
    ).mappings().all()

# information_schema는 MySQL이 테이블, 컬럼 같은 메타 정보를 저장하는 시스템 DB입니다.
# 여기서는 현재 실습 DB에 어떤 테이블이 있는지 확인합니다.
pd.DataFrame(rows)

        TABLE_NAME
0          courses
1      enrollments
2         payments
3  python_students
4         students

## 4. SQLAlchemy Core로 테이블 정의하기

Core는 테이블과 SQL 문을 Python 객체로 표현합니다. ORM보다 SQL에 더 가까운 방식입니다.

In [4]:
# MetaData는 SQLAlchemy Core에서 테이블 정의들을 묶어 관리하는 객체입니다.
# 여러 Table 객체를 한 번에 create_all(), drop_all()로 처리할 수 있게 해줍니다.
metadata = MetaData()

# Table 객체는 실제 DB 테이블 구조를 Python 코드로 표현합니다.
# 첫 번째 인자는 테이블 이름, 두 번째 인자는 이 테이블이 소속될 MetaData입니다.
sa_students = Table(
    "sqlalchemy_students",
    metadata,
    # Column()은 테이블의 컬럼 하나를 정의합니다.
    # primary_key=True는 기본키, autoincrement=True는 자동 증가 컬럼을 의미합니다.
    Column("student_id", Integer, primary_key=True, autoincrement=True, comment="학생을 식별하는 자동 증가 기본키"),

    # nullable=False는 반드시 값이 들어가야 한다는 뜻입니다.
    Column("name", String(50), nullable=False, comment="학생의 이름"),

    # unique=True는 같은 이메일이 두 번 들어가지 못하게 하는 제약 조건입니다.
    Column("email", String(120), nullable=False, unique=True, comment="학생의 이메일, 중복 불가"),

    # 점수처럼 소수점 자릿수가 중요한 값은 Numeric을 사용합니다.
    # Numeric(5, 2)는 전체 5자리, 소수점 아래 2자리까지 저장한다는 뜻입니다.
    Column("score", Numeric(5, 2), comment="SQLAlchemy 실습의 점수"),

    # server_default=func.now()는 Python 시간이 아니라 MySQL 서버 시간을 기본값으로 넣게 합니다.
    Column("created_at", DateTime, nullable=False, server_default=func.now(), comment="데이터 등록 시간"),
    comment="SQLAlchemy Core 실습용 학생 테이블",
)

# 실습을 여러 번 실행해도 같은 결과가 나오도록 기존 테이블을 지우고 다시 만듭니다.
# checkfirst=True를 사용하면 테이블 존재 여부를 먼저 확인해서 불필요한 오류를 피합니다.
metadata.drop_all(engine, tables=[sa_students], checkfirst=True)
metadata.create_all(engine, tables=[sa_students])

print("sqlalchemy_students 테이블 준비 완료")

sqlalchemy_students 테이블 준비 완료

## 5. Core로 INSERT와 SELECT 실행하기

`engine.begin()` 블록은 정상 종료 시 자동으로 commit하고, 오류가 나면 rollback합니다.

In [5]:
# Core의 insert()는 Table 객체를 기준으로 INSERT 문을 만듭니다.
# 딕셔너리의 key는 컬럼명과 같아야 하며, value가 실제로 저장될 데이터입니다.
# score는 Numeric 컬럼이므로 Decimal을 사용해 소수점 값을 정확하게 표현합니다.
student_rows = [
    {"name": "김민준", "email": "sa_minjun@example.com", "score": Decimal("92.50")},
    {"name": "이서연", "email": "sa_seoyeon@example.com", "score": Decimal("85.00")},
    {"name": "최도윤", "email": "sa_doyun@example.com", "score": Decimal("78.00")},
]

# engine.begin()은 트랜잭션을 자동으로 시작합니다.
# 블록이 정상 종료되면 commit, 중간에 오류가 발생하면 rollback이 자동으로 실행됩니다.
with engine.begin() as conn:
    # 두 번째 인자로 딕셔너리 목록을 넘기면 여러 행을 한 번에 INSERT합니다.
    conn.execute(insert(sa_students), student_rows)

# select(sa_students)는 SELECT * FROM sqlalchemy_students와 비슷한 의미입니다.
# sa_students.c.student_id에서 c는 column collection, 즉 이 테이블의 컬럼 모음입니다.
stmt = select(sa_students).order_by(sa_students.c.student_id)

with engine.connect() as conn:
    # stmt는 아직 SQL을 실행한 결과가 아니라 SQL 문을 표현한 객체입니다.
    # conn.execute(stmt)를 호출하는 순간 실제 DB에 SQL이 전송됩니다.
    rows = conn.execute(stmt).mappings().all()

pd.DataFrame(rows)

           created_at                   email name  score  student_id
0 2026-06-29 01:23:15   sa_minjun@example.com  김민준  92.50           1
1 2026-06-29 01:23:15  sa_seoyeon@example.com  이서연  85.00           2
2 2026-06-29 01:23:15    sa_doyun@example.com  박도윤  78.00           3

## 6. Core로 조건 조회, 수정, 삭제하기

In [6]:
# DECIMAL/NUMERIC 값은 float보다 Decimal로 다루면 소수점 오차를 줄일 수 있습니다.
minimum_score = Decimal("80.00")

# select(), where(), order_by()를 연결해 SQL SELECT 문을 Python 코드로 조립합니다.
# 이 방식은 문자열 SQL보다 자동완성, 재사용, 조건 조합에 유리합니다.
stmt = (
    select(sa_students.c.name, sa_students.c.email, sa_students.c.score)
    # WHERE score >= 80.00 조건을 만드는 부분입니다.
    .where(sa_students.c.score >= minimum_score)
    # ORDER BY score DESC 조건을 만드는 부분입니다.
    .order_by(sa_students.c.score.desc())
)

with engine.connect() as conn:
    rows = conn.execute(stmt).mappings().all()

pd.DataFrame(rows)

                    email name  score
0   sa_minjun@example.com  김민준  92.50
1  sa_seoyeon@example.com  이서연  85.00

In [7]:
with engine.begin() as conn:
    # update()와 delete()도 Table 객체의 컬럼을 기준으로 조건을 작성합니다.
    # 아래 코드는 이메일이 sa_minjun@example.com인 학생의 점수를 95.00으로 바꿉니다.
    conn.execute(
        update(sa_students)
        .where(sa_students.c.email == "sa_minjun@example.com")
        .values(score=Decimal("95.00"))
    )

    # DELETE도 WHERE 조건을 꼭 확인해야 합니다.
    # 조건 없이 delete(sa_students)를 실행하면 테이블의 모든 행이 삭제될 수 있습니다.
    conn.execute(delete(sa_students).where(sa_students.c.email == "sa_doyun@example.com"))

with engine.connect() as conn:
    # 변경 후 남아 있는 데이터를 다시 조회해 UPDATE와 DELETE 결과를 확인합니다.
    rows = conn.execute(select(sa_students).order_by(sa_students.c.student_id)).mappings().all()

pd.DataFrame(rows)

           created_at                   email name  score  student_id
0 2026-06-29 01:23:15   sa_minjun@example.com  김민준  95.00           1
1 2026-06-29 01:23:15  sa_seoyeon@example.com  이서연  85.00           2

## 7. ORM 기초 맛보기

ORM은 테이블을 Python 클래스로 표현합니다. 아래 예제는 같은 데이터베이스에 별도 ORM 실습 테이블을 만듭니다.

In [8]:
# DeclarativeBase를 상속한 Base는 ORM 클래스들을 등록하는 기준점입니다.
# 앞으로 만드는 ORM 클래스는 Base.metadata에 테이블 정보로 모입니다.
class Base(DeclarativeBase):
    pass


# ORM에서는 Python 클래스 하나가 DB 테이블 하나에 대응됩니다.
# Core의 Table은 "테이블을 직접 다루는 방식"이고,
# ORM 클래스는 "테이블의 한 행을 Python 객체처럼 다루는 방식"입니다.
class OrmStudent(Base):
    __tablename__ = "sqlalchemy_orm_students"
    __table_args__ = {"comment": "SQLAlchemy ORM 실습용 학생 테이블"}

    # Mapped[...]는 이 속성이 DB 컬럼과 매핑된다는 타입 힌트입니다.
    # mapped_column()은 실제 컬럼 타입, 기본키, 제약 조건을 정의합니다.
    student_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True, comment="학생의 ID")
    name: Mapped[str] = mapped_column(String(50), nullable=False, comment="학생의 이름")
    email: Mapped[str] = mapped_column(String(120), nullable=False, unique=True, comment="학생의 이메일")

    # score는 None이 될 수도 있으므로 Mapped[Decimal | None]으로 표시합니다.
    score: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), comment="점수")

    # created_at은 DB 서버가 기본값을 넣어 주므로 객체를 만들 때 직접 넘기지 않아도 됩니다.
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), comment="등록 시간")


# ORM 클래스에 연결된 테이블만 다시 생성합니다.
# Base.metadata에는 ORM 클래스들이 만든 테이블 정의가 들어 있습니다.
Base.metadata.drop_all(engine, tables=[OrmStudent.__table__], checkfirst=True)
Base.metadata.create_all(engine, tables=[OrmStudent.__table__])

# Session은 ORM 객체를 DB에 저장하고 조회하는 작업 단위입니다.
# add_all()로 객체를 Session에 올리고 commit()해야 실제 DB에 반영됩니다.
with Session(engine) as session:
    session.add_all([
        OrmStudent(name="박하은", email="orm_haeun@example.com", score=Decimal("91.00")),
        OrmStudent(name="정지후", email="orm_jihu@example.com", score=Decimal("82.50")),
    ])
    session.commit()

with Session(engine) as session:
    # scalars()는 SELECT 결과에서 ORM 객체만 꺼내고 싶을 때 사용합니다.
    # 결과의 각 항목은 딕셔너리가 아니라 OrmStudent 객체입니다.
    students = session.scalars(select(OrmStudent).order_by(OrmStudent.score.desc())).all()

# 화면에 보기 좋게 필요한 속성만 딕셔너리로 바꿔 출력합니다.
[{"name": student.name, "email": student.email, "score": student.score} for student in students]

[{'name': '최하은', 'email': 'orm_haeun@example.com', 'score': Decimal('91.00')},
 {'name': '정지후', 'email': 'orm_jihu@example.com', 'score': Decimal('82.50')}]